"""add employee_meetings association table

Revision ID: bf5865bb85a7
Revises: 62294547afe0
Create Date: 2024-07-17 12:47:26.167318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5865bb85a7'
down_revision = '62294547afe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee.id', sa.Integer(), nullable=False),
    sa.Column('meetings.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee.id'], ['employees.id'], name=op.f('fk_employees_meetings_employee.id_employees')),
    sa.ForeignKeyConstraint(['meetings.id'], ['meetings.id'], name=op.f('fk_employees_meetings_meetings.id_meetings')),
    sa.PrimaryKeyConstraint('employee.id', 'meetings.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###
