"""finally fixed i hope

Revision ID: c4865dcaaa1f
Revises: ac68e10ec824
Create Date: 2024-07-17 13:34:53.380872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4865dcaaa1f'
down_revision = 'ac68e10ec824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('assignments', 'state_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('state_date', sa.DATETIME(), nullable=True))
    op.drop_column('assignments', 'start_date')
    # ### end Alembic commands ###
